name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  # ======================================================================================================
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get a Latest Tag Name
        id: get_latest_tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash

      - name: Update the Latest Release
        id: update_latest_release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
    outputs:
      upload_url: ${{ steps.update_latest_release.outputs.upload_url }}

  # ======================================================================================================
  build-and-upload-assets:
    needs: prepare-release
    name: Build and Upload Assets
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.1' # The Go version to download.

      - name: Get a Build Script
        id: get_build_script
        uses: juliangruber/read-file-action@v1
        with:
          path: ./build.ps1

      - name: Run the Build Script
        id: run_build_script
        uses: Amadevus/pwsh-script@v2
        with:
          script: ${{ steps.get_build_script.outputs.content }}
          
  