name: Release

on:
  workflow_dispatch:

jobs:
  build-and-upload-assets:
    name: Build and Upload Assets
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup .NET 7 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
        
      - name: Run the Build Script
        run:
          ./scripts/publish_icon.ps1
        shell: pwsh
