name: Build on Release

on:
  release:
    types: [published]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find a Tag
        id: find_tag
        uses: pozetroninc/github-action-get-latest-release@master
        with: 
          owner: project-toybox
          repo: toybox-image-conversion-server
          excludes: draft        

      - name: Update the Latest Release
        id: update_latest_release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ steps.find_tag.outputs.release }}
    outputs:
      upload_url: ${{ steps.update_latest_release.outputs.upload_url }}

  build-and-upload-assets:
    needs: prepare
    name: Build and Upload Assets
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Read the VERSION
        id: read_version_info
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION
        
      - name: Run the Build Script
        run:
          ./build.ps1
        shell: pwsh

      - name: Upload Assets(x86)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ needs.prepare.outputs.upload_url }}
          asset_path: ./dist/toybox-ics-v${{ steps.read_version_info.outputs.content }}-x86.zip
          asset_name: toybox-ics-v${{ steps.read_version_info.outputs.content }}-x86.zip
          asset_content_type: application/zip

      - name: Upload Assets(x64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ needs.prepare.outputs.upload_url }}
          asset_path: ./dist/toybox-ics-v${{ steps.read_version_info.outputs.content }}-x64.zip
          asset_name: toybox-ics-v${{ steps.read_version_info.outputs.content }}-x64.zip
          asset_content_type: application/zip